version: 2
updates:
  
  # This entry handles your .toml file AND any .gradle files
  - package-ecosystem: "gradle"
    directory: "/" 
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "dependabot"
    # Optional: This group will batch all "androidx.*" updates
    # from your .toml file into a single PR.
    groups:
       androidx:
         patterns:
           - "androidx.*"

  # (Recommended) This keeps your GitHub Actions workflows up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "ci"
      - "dependabot"
